const mongoose=require('mongoose'),
Schema=mongoose.Schema,
GroupSchema=new Schema({
    admins:[{
        user:{
            type:Schema.Types.ObjectId,
            ref:'person'
        },
        username:{
            type:String
        }
    }],
    name:{
        type:String,
        required:true
    },
    members:[{
        user:{
            type:Schema.Types.ObjectId,
            ref:'person'
        },
        username:{
            type:String
        },
        isAdmin:{
            type:Boolean,
            default:false
        }
    }],
    posts:[{
        user:{
            type:Schema.Types.ObjectId,
            ref:'profile'
        },
        bod:{
            type:String,
        },
        date:{
            type:Date,
            default:Date.now
        },
        upvotes:[
            {
                user:{
                    type:Schema.Types.ObjectId,
                    ref:'person'
                }
            }
        ],
        downvotes:[
            {
                user:{
                    type:Schema.Types.ObjectId,
                    ref:'person'
                }
            }
        ],
        comments:[
            {
            user:{
                type:Schema.Types.ObjectId,
                ref:'person'
            },
            text:{
                type:String
            },
            date:{
                type:Date,
                default:Date.now
            },
            reply:[
                {
                    user:{
                        type:Schema.Types.ObjectId,
                        ref:'person'
                    },
                    text:{
                        type:String
                    },
                    date:{
                        type:Date,
                        default:Date.now
                    } 
                }
            ]
    }
]
    }],
});
module.exports=mongoose.model('group',GroupSchema);

