const mongoose=require('mongoose'),
Schema=mongoose.Schema;
const ProfileSchema=new Schema({
user:{
    type:Schema.Types.ObjectId,
    ref:'person'
},
personal:{
    username:{
        type:String,
        required:true
    },
    age:{
        type:Number,
        required:true
    },
    phone:{
        type:Number,
        required:true
    },
    profilepic:{
        type:String,
        default:"https://d1nhio0ox7pgb.cloudfront.net/_img/g_collection_png/standard/256x256/delivery_man.png"
    },
    gender:{
        type:String,
        required:true
    }
},
residence:{
    address:{
        type:String,
    },
    city:{
        type:String,
    },
    state:{
        type:String, 
    },
    country:{
        type:String, 
    }
},
social:[
    {
        socialmedia:{
            type:String
        },
        url:{
            type:String
        },
        active:{
            type:Boolean
        }
    }
],
timeline:[
    {
        user:{
            type:Schema.Types.ObjectId,
            ref:'profile'
        },
        bod:{
            type:String,
        },
        date:{
            type:Date,
            default:Date.now
        },
        upvotes:[
            {
                user:{
                    type:Schema.Types.ObjectId,
                    ref:'person'
                }
            }
        ],
        downvotes:[
            {
                user:{
                    type:Schema.Types.ObjectId,
                    ref:'person'
                }
            }
        ],
        comments:[
            {
            user:{
                type:Schema.Types.ObjectId,
                ref:'person'
            },
            text:{
                type:String
            },
            date:{
                type:Date,
                default:Date.now
            },
            reply:[
                {
                    user:{
                        type:Schema.Types.ObjectId,
                        ref:'person'
                    },
                    text:{
                        type:String
                    },
                    date:{
                        type:Date,
                        default:Date.now
                    } 
                }
            ]
    }
]
    }
]
});

module.exports=mongoose.model('profile',ProfileSchema);
